### ISSUE TITLE
Integrate Sentry with github

### ISSUE THREAD

**Issue by gabriofr** [mong/qmongjs#121]

**Comment by gabriofr** [comment]
@areedv : I forbindelse med dette så skal det ha kommet en request fra sentry til deg på epost, man må være "owner" for å kunne installere integrasjonene. :)

**Comment by gabriofr** [comment]
Tror jeg mangler noen rettigheter på github, ser dere noe på den siden? 

![image](https://user-images.githubusercontent.com/1658284/102991351-50fa1e00-4519-11eb-876b-55f64648ad7f.png)

**Comment by arnfinn** [comment]
Jeg prøvde å godkjenne Sentry, men er nok ikke `Owner or Manager of your Sentry org.`. Mulig @areedv må gjøre det?

**Comment by gabriofr** [comment]
> Jeg prøvde å godkjenne Sentry, men er nok ikke `Owner or Manager of your Sentry org.`. Mulig @areedv må gjøre det?

Den ble sånn halvveis godkjent ser det ut som, man må nok være øverst i hierarkiet på begge sider. Tar Juleferie nå så vi får se på det til neste år :) God Jul!

**Comment by areedv** [comment]
Godt nyttår! Ikke helt sikker på hva jeg ev bør/må gjøre her...

**Comment by arnfinn** [comment]
Mulig du må gjøre noe på sentry.io? Jeg aktiverte Sentry på github: https://github.com/organizations/mong/settings/installations/13695446 men har ikke konto/organisasjon på sentry.io.

**Comment by gabriofr** [comment]
Stoppa for meg siden jeg ikke har rettigheter nok på github siden og for @arnfinn siden han ikke har rettigheter nok på sentry. Så vi trenger en som har høye nok retigheter begge steder til å gå inn her: https://sentry.io/settings/skde/integrations/github  og trykke på "Add Installation"

![image](https://user-images.githubusercontent.com/1658284/103526889-d2d73900-4e81-11eb-8960-ce0cdadab17a.png)
![image](https://user-images.githubusercontent.com/1658284/103526977-f1d5cb00-4e81-11eb-80b5-8daf8b0d60e8.png)

Ligger en halvveis godkjent en for qmongjs, men jeg tror vi vil ha All Repositories

**Comment by areedv** [comment]
Takk for veiledning. Jeg har (forhåpentligvis) installert sentry.io på mong, for alle "repositories"...

**Comment by gabriofr** [comment]
> Takk for veiledning. Jeg har (forhåpentligvis) installert sentry.io på mong, for alle "repositories"...

snodige greier, ser ikke at den er installert og kan derfor ikke sette den opp, har du noe annet i dette skjermbildet?: 
![image](https://user-images.githubusercontent.com/1658284/103638100-b81dc680-4f4c-11eb-9bc0-c264259527d0.png)

**Comment by gabriofr** [comment]
@areedv : Ligger dokumentasjon her, med noen ting du kan sjekke om man har problemer.
https://docs.sentry.io/product/releases/setup/release-automation/

Tenker spesielt på det som står litt ned på siden, siden både jeg og Arnfinn fikk til sånn halveis... 

> If you’re having trouble adding the integration, disconnect then reconnect your GitHub identity.

**Comment by gabriofr** [comment]
Bump

**Comment by areedv** [comment]
Hm, har ikke klart å finne ut av det, og  nå må jeg løpe. Kan det være at vi faktisk må betale noe i Sentry? Og hva betyr egentlig reconnect your GitHub identity? Mulig du @gabriofr skal få en adnmintilgang i mong org på github sånn at vi ikke kaster bort mer tid på dette...

**Comment by gabriofr** [comment]
Skal ikke koste mer, man må bare være eier av både gitrepoen og sentry. Hvis du midlertidig kan gjøre meg til admin i mong org så skal jeg finne ut av det :)

**Comment by arnfinn** [comment]
@gabriofr Nå har jeg satt deg til mong-eier.

**Comment by gabriofr** [comment]
@arnfinn: Takk, fant ut av det tilslutt, måtte fjerne alt og starte prosessen på ny. Irriterende lite feilmeldinger i prosessen før jeg fant ut det. Men nå er i alle fall integrasjonen på plass :)

https://sentry.io/settings/skde/integrations/github/85100/

**Comment by arnfinn** [comment]
Glimrende:)
