### ISSUE TITLE
Add disclaimer when app is opened in old browser

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#24]
The app will not work in *IE*, old versions of *Edge*, and maybe other (old) browsers. A disclaimer should be shown telling people to use another (newer) browser.

**Comment by arnfinn** [comment]
Finn ut hvilke versjoner av Edge etc. der det må opprettes advarsel.

**Comment by gabsinator** [comment]
I tired with several react libraries with additional features, but none of them would work with MSiE as the compiled ES version is not supported.

The test in the code makes use of MSiEs conditional compilation of comment contents in. If IE sees this comment, it actually compiles the contents of comment blocks as pure code. Now the trick happens with the ! in the comment. IE compiles the ! as if it were written into source so it handles the code as if (!false), while all other browsers treat it as if (false).

Testet on Windows8 with MSiE in a virtualbox image, needs update if other browser needs detecting.
