### ISSUE TITLE
Fix sentry

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#302]
App can not connect to Sentry:

![image](https://user-images.githubusercontent.com/136346/110909316-411bfa00-8310-11eb-8c29-9c8da9a66b15.png)

**Comment by arnfinn** [comment]
@areedv Legger du Yohannes og meg inn i Sentry-organisasjonen (min gmail-adresse) på https://sentry.io/?

**Comment by areedv** [comment]
Vi må betale for å ha flere brukere og jeg ønsker ikke å bruke tid på å ordne med kredittkort fra rhf-et akkurat nå. Som en midlertidig løsning, kan du @arnfinn overta min bruker? Dette er tross alt mer relevant for deg og/eller @yte0

**Comment by arnfinn** [comment]
Ja, jeg kan overta. Så sender jeg den videre til @yte0 hvis jeg ikke får det til:)

**Comment by arnfinn** [comment]
@areedv sender du meg info?

**Comment by arnfinn** [comment]
Det kan se ut til at uBlock (en adblocker) stopper sendingene til Sentry. Dette er kanskje like greit? https://github.com/getsentry/sentry-javascript/issues/2916
