### ISSUE TITLE
Indikatorer med gjennomsnittsverdi

### ISSUE THREAD

**Issue by lenaringstado** [mong/qmongjs#303]
Flere registre har kvalitetsindikatorer som beregnes som en gjennomsnittsverdi. Slike indikatorer kan legges inn på samme måte som andels-indikatorer, men må være aggregert til laveste nivå før de legges inn. Det vi mangler, er informasjon om at dette er en gjennomsnittsverdi og ikke en andel, slik at man kan få riktige benevninger i en figur.

**Comment by arnfinn** [comment]
## Notat

Eksempeldata http://localhost:3000/kvalitetsregistre/roas/sykehus?chart_type=bar&selected_row=roas_gjsnitt_kriser&selected_treatment_units=Skien
