### ISSUE TITLE
Show date and time for last data delivery

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#35]
Use the `time` column from `agg_data`.

On each indicator. Maybe under "Om indikatoren"?

**Comment by arnfinn** [comment]
Ny tidskolonne i `agg_data`? Lage view?

**Comment by arnfinn** [comment]
![image](https://user-images.githubusercontent.com/136346/143005756-a035023f-bc0a-4f10-9663-c98a67dfcb6d.png)

**Comment by areedv** [comment]
Hvis det er slik at aktuelle data (siste tidspunkt for levering) allerede finnes i data så bør vel @yte0 tas seg av implementeringen, altså å legge til litt tekst i "Om kvalitetsindikatoren" før den vises frem i applikasjonen?

**Comment by arnfinn** [comment]
@areedv Ja, du har gjort din del av jobben her, så fjerner deg fra "Assigness":)

**Comment by arnfinn** [comment]
@yte0 Jeg kan prøve meg på denne.
