### ISSUE TITLE
Prosent i stolpediagram

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#566]
Noe ala dette:
![image](https://user-images.githubusercontent.com/136346/121194211-d591ec00-c86e-11eb-93b9-eb37c3846554.png)

**Comment by gabriofr** [comment]
@arnfinn : Har jeg funnet en bug eller skal det være slik?
Hvis jeg går rett inn og klikker på en idikator, så får jeg et linjediagram med bare Nasjonalt, slik: 
![image](https://user-images.githubusercontent.com/1658284/123983407-21463a00-d9c4-11eb-8eb3-1e7783a4db8b.png)

Hvis jeg da klikker på "Søyle" så kommer det opp en bunch til ,slik: 
![image](https://user-images.githubusercontent.com/1658284/123983609-4a66ca80-d9c4-11eb-9c46-0c985a0c6e0f.png)

Ser ikke helt hvorfor de er der når jeg ikke har valgt noen av dem

**Comment by arnfinn** [comment]
Neida, det er ikke en bug. I stolpediagrammet skal man enkelt kunne sammenligne alle enheter. Hvis man velger en enhet vil denne få en litt annen farge. Linjediagram med alle enheter vil bare se ut som spaghetti. #55
