### ISSUE TITLE
Merkelige farger hvis målnivå er feil

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#583]
Grønt satt til 100%

Orange satt til 3%

![image](https://user-images.githubusercontent.com/136346/120813941-addd1400-c54e-11eb-9068-bb6392a14bb3.png)

![image](https://user-images.githubusercontent.com/136346/120813730-7706fe00-c54e-11eb-8806-100fcc0569ad.png)

**Comment by arnfinn** [comment]
@areedv Er det mulig å legge inn en sjekk i databasen som ser om grønt nivå er satt lik eller lavere enn orange nivå hvis `direction == 0` (og motsatt hvis `direction == 1`)?

**Comment by areedv** [comment]
Tror i så fall at det må være noe som foregår i imongr. Kanskje en slik funksjon kan legges bake knappen "Rydd aggregerte data"?
![image](https://user-images.githubusercontent.com/1522857/121177069-403a2c00-c85d-11eb-8372-2b55db6873d5.png)

**Comment by arnfinn** [comment]
Ja. Eventuelt en ny knapp: "Sjekk database".

**Comment by areedv** [comment]
Joda, det går faktisk an å legge inn som en constraint i databasen, har testet følgende på tabellen "tind" (kopi av ind uten data):
```sql
alter table tind
  add constraint level_green_greater_than_yellow
    check (case
      when level_direction = 1
           and level_green > level_yellow
      then true
      else false end),
  add constraint level_green_lesser_than_yellow
    check (case
      when level_direction = 0
           and level_green < level_yellow
      then true
      else false end)
```

Nais! Men, det vil muligens ikke la seg implementere i ind-tabellen fordi nåværende data bryter med de forutsetningen som forsøkes lagt inn ;-) Hvem retter opp?

**Comment by arnfinn** [comment]
Jeg skal ha rettet den ene feilen jeg vet om i `prod` og `verify`. Hjelper det hvis du bytter om `>` og `<` med `>=` og `<=`? For det skal være lov (hvis man ikke har gult målnivå).

**Comment by areedv** [comment]
Ok, detta blir bra!

**Comment by areedv** [comment]
Hm, vi har level_*-felter med NULL. Det fungerer dårlig i denne sammenhengen. Burde det være et krav (constraint) at disse ikke kan være NULL? 
![image](https://user-images.githubusercontent.com/1522857/121191498-500d3c80-c86c-11eb-97a9-561c24812f53.png)

**Comment by arnfinn** [comment]
Vi har flere indikatorer der vi ikke har målnivå. Se f.eks https://skde.org/kvalitetsregistre/noric?selected_row=noric_pacemaker (usikker på hvorfor ikke `level_direction` er `NULL` på disse). Så jeg vet ikke helt om det er greit å kreve at alle indikatorene skal ha målnivå.

**Comment by areedv** [comment]
Ok, da må jeg finne en annen måte å definerer hva som kan betraktes som konsistent (og ikke)

**Comment by arnfinn** [comment]
Closed with https://github.com/mong/imongr/pull/125
