### ISSUE TITLE
Designforslag fargepalett. Helse-Nord profil

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#59]

**Comment by ChinaViking** [comment]
![Designforslag](https://user-images.githubusercontent.com/3600543/100865300-6f7b7500-3497-11eb-92cf-9f3e94d84866.jpg)

![tidligere](https://user-images.githubusercontent.com/3600543/100865496-b36e7a00-3497-11eb-915a-5ed66df3604e.jpg)
