### ISSUE TITLE
Linjediagram: punkter for hvert dataopunkt

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#610]
Slik det er nå så er det nesten umulig å se data hvis det finnes kun ett datapunkt (Volda under). Det er også umulig å vite at en linje kan mangle et datapunkt mellom to (Førde har ikke data for 2017).

Ved å sette inn punkter og ikke bare linjer vil man kunne se dette bedre.

Noe slikt:
![image](https://user-images.githubusercontent.com/136346/121670650-f6945000-caad-11eb-8955-f01c88b0759c.png)

**Comment by gabriofr** [comment]
Er godt i gang med denne, har en issue med at "prikkene" tegnes for hvert steg i animasjonen. Har måtte legge denne litt på hylla pga kapasitet, men starter snart igjen :)
