### ISSUE TITLE
Målnivå legges på feil

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongjs#680]
### Se på et linjediagram

![image](https://user-images.githubusercontent.com/136346/123759354-1b673080-d8c0-11eb-88a5-7092cee48a51.png)

### Sett på målnivå

![image](https://user-images.githubusercontent.com/136346/123759482-3b96ef80-d8c0-11eb-8cc5-5703b85e9af8.png)

### Bytt til stolpediagram

![image](https://user-images.githubusercontent.com/136346/123759806-89135c80-d8c0-11eb-822c-7e9891b67bd9.png)

**Comment by gabriofr** [comment]
@arnfinn : denne er nok forårsaket av samme "bug" jeg fant i `Chart.tsx`. 
Der den begynner å tegne grafen før dataen er ferdig lastet fra api, er mao allerede fikset i PR #691 hvor denne grafen nå ser slik ut: 
![image](https://user-images.githubusercontent.com/1658284/124573120-8c22c580-de49-11eb-8285-0695821912a5.png)

**Comment by gabriofr** [comment]
Lukker bare denne, bekrefter at den blir fikset av #691
