### ISSUE TITLE
Sette opp ny infra på AWS

### ISSUE THREAD

**Issue by LarsJK** [mong/qmongjs#99]

**Comment by LarsJK** [comment]
@areedv Did you want to collaborate on this or should I set something up and discuss later?

**Comment by areedv** [comment]
Please go ahead. Discussion later :smile:

**Comment by LarsJK** [comment]
@areedv @yte0 @arnfinn 

Setup a sample on my account and am ready to move it over to yours:

http://larsjk-mong.s3-website-eu-west-1.amazonaws.com

**Comment by LarsJK** [comment]
@areedv 

I have moved the infrastructure over to the SKDE account.

To finish this issue we need to complete these tasks:

- [ ] Connect imongr to the new db.
- [ ] Setup the domain on Cloudflare.
- [ ] Tear down the old infrastructure.

We may need to do these tasks together, and plan when to make the switch.
